books/Books/Books/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.urls import path, include
from home.views import landing_page, LandingPageView, SignupView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('books/', include('home.urls', namespace="books")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/Books/home/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView
from . import views


app_name = "home"

urlpatterns = [
    
    
    # path('', views.home, name='home'),
    path('books/', BookListView.as_view(), name='book-list'),
    path('<int:pk>/', BookDetailView.as_view(), name='book-details'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book-update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book-delete'),
    path('create/', BookCreateView.as_view(), name='create-book'),
    path('new_borrower/', views.new_borrower, name='new-borrower')
   

    
]

books/Books/home/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
	pass

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username
    


class Book(models.Model):
    Book_Title = models.CharField(max_length=255)
    ISBN_Number = models.IntegerField()
    DatePublished = models.DateField()
    category = models.CharField(max_length=255)
    author = models.CharField(max_length=255)    
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.Book_Title)

class Borrower(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)    
    booksBorrowed = models.IntegerField()
    dateBorrowed = models.DateField()
    dateToReturn = models.DateField()
    status = models.BooleanField(default=False)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    
   
post_save.connect(post_user_created_signal, sender=User)

        

books/Books/home/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Borrower, Book


User = get_user_model()

class BorrowerModelForm(forms.ModelForm):
    class Meta:
        model = Borrower
        fields = (
            'user',
            'booksBorrowed',
            'dateBorrowed',
            'dateToReturn',
            'status',
            )

class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'Book_Title',
            'ISBN_Number',
            'DatePublished',
            'category',
            'author',
            'status'


        )


class BookForm(forms.Form):
    Book_Title = forms.CharField()
    ISBN_Number = forms.IntegerField()
    DatePublished = forms.DateField()
    category = forms.CharField()
    author = forms.CharField()
    status = forms.BooleanField()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField }

books/Books/Books/views.py
from django.shortcuts import render

books/Books/home/views.py
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Book, User, Borrower
from .forms import BookForm, BorrowerModelForm, BookModelForm, CustomUserCreationForm

# Create your views here.


#we are going to replace the function based views into classBased views
class SignupView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')



class LandingPageView(TemplateView):
    template_name = 'landing.html'



def landing_page(request):
    return render(request, 'landing.html')


class BookListView(LoginRequiredMixin, ListView):
    template_name = 'books.html'
    queryset = Book.objects.all()
    context_object_name = 'books'


def allbooks(request):
    books = Book.objects.all()   
    context = {  
    "books":books
    }
    return render(request, 'books.html', context)

class BookDetailView(LoginRequiredMixin, DetailView):
    template_name = 'bookDetailed.html'
    queryset = Book.objects.all()
    context_object_name = 'book'

def book_details(request, pk):
    book = Book.objects.get(id=pk)
    context = {
    "book":book
    }
    
    return render(request, 'bookDetailed.html', context)

class BookCreateView(LoginRequiredMixin, CreateView):
    template_name = 'bookCreate.html'
    form_class = BookForm

    def get_success_url(self):
        return reverse('books:book-list')
    
    def form_valid(self, form):
        # TODO: send email
        send_mail()
        return super(BookCreateView, self).form_valid(form)
    


def create_book(request):
    form = BookForm()
    if request.method == 'POST':
        print('receiving a post request') 
        form = BookForm(request.POST)
        if form.is_valid():
           
            Book_Title = form.cleaned_data['Book_Title']
            ISBN_Number = form.cleaned_data['ISBN_Number']
            DatePublished = form.cleaned_data['DatePublished']
            category = form.cleaned_data['category']
            author = form.cleaned_data['author']
            status = form.cleaned_data['status']
            
            Book.objects.create(
                Book_Title=Book_Title,
                ISBN_Number=ISBN_Number,
                DatePublished=DatePublished,
                category=category,
                author=author,
                status=status)
           
            return redirect('/books')

                  
       

    context = {
        'form': form
    }

    return render(request, 'bookCreate.html', context)


def new_borrower(request):
    form = BorrowerModelForm()
    if request.method == 'POST':
        form = BorrowerModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/books')
    context = {
        'form': form
    }

    return render(request, 'borrowerCreate.html', context)

class BookUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'bookUpdate.html'
    queryset = Book.objects.all()
    form_class = BookForm

    def get_success_url(self):
        return reverse('books:book-list')

def book_update(request, pk):
    book = Book.objects.get(id=pk)
    form = BookModelForm(instance=book)
    
    if request.method == 'POST':
        form = BookModelForm(request.POST, instance=book)        
        if form.is_valid():
            form.save()
            
            return redirect('/books')

    context = {
        'form': form,
        'book': book
    }
    return render(request, 'bookUpdate.html', context=context)

class BookDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'bookDelete.html'
    form_class = BookForm

    def get_success_url(self):
        return reverse('books:book-list')

def book_delete(request, pk):
    book = Book.objects.get(id=pk)
    book.delete()
    return redirect('/books')
    

   

books/Books/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>	Books APP</title>
	<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
	{% include 'navbar.html' %}
{% block content %}


{% endblock content %}
</body>
</html>

books/Books/templates/bookCreate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Create a new book</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>

    </form>
     
      
      

       
    



{% endblock %}

books/Books/templates/bookDelete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Are you sure you want to delete this book?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>

    </form>
  

{% endblock %}

books/Books/templates/bookDetailed.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Book</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ book.Book_Title }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'books:book-list'%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'books:book-update' book.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update details</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Author</span>
            <span class="ml-auto text-gray-900">{{ book.author }}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Category</span>
            <span class="ml-auto text-gray-900">{{ book.category }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Year Published </span>
            <span class="ml-auto text-gray-900">{{ book.DatePublished }}</span>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

    <h1>{{ book.Book_Title }} Details </h1>
    ISBN Number :  {{ book.ISBN_Number }} </br>
    Published on: {{ book.DatePublished }}</br>
    The Author is: {{ book.author }}</br>
    {{ book.Book_Title }} falls under {{ book.category }} Category </br>

    <hr />

    <a href="{% url 'books:book-update' book.pk %}">Update Book Details</a>
    <a href="{% url 'books:book-delete' book.pk %}">Delete Book</a>

    <a href="{% url 'books:book-list'%}">Go back to all available books</a>

    

       
{% endblock %}

books/Books/templates/bookUpdate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Book</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ book.Book_Title }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'books:book-details' book.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'books:book-update' book.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update details</a>
          </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button  type="submit">Submit</button>
        
            </form>
          <a href="{% url 'books:book-delete' book.pk %}" ><button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete Book</button></a>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

   

    

    

       
{% endblock %}




 
      
      

       
    

books/Books/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Books</h1>
                </div> 
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'books:create-book' %}">Create a new Book</a>
                </div>
            </div> 
        <div class="flex flex-wrap -m-4">
            {% for book in books %}            
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                            <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                            <circle cx="12" cy="7" r="4"></circle>
                        </svg>
                        </div>
                            <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ book.Book_Title }} |  {{ book.author}}</h2>
                            <p class="leading-relaxed text-base">
                                Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                            <a href=" {% url 'books:book-details' book.pk  %}" class="mt-3 text-indigo-500 inline-flex items-center">More about this Books
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                            </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </section>

        



{% endblock %}

books/Books/templates/borrowerCreate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Create a new Reader</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>

    </form>
     
      
      

       
    



{% endblock %}

books/Books/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Welcome to the Books Club</h1>
      
     <a href=" {% url 'books:book-list' %}">Books</a> </br>
     </br>
     <a href="{% url 'books:new-borrower'%}">Sign up for borrowing</a>      
    



{% endblock content %}

books/Books/templates/landing.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Hello Books</h1>
        <p class="mb-8 leading-relaxed">Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over meditation PBR&B pickled ennui celiac mlkshk freegan photo booth af fingerstache pitchfork.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>

  {% endblock content %}

books/Books/templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a  href="{% url 'landing-page' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Books App</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        
        <a href="{% url 'books:book-list'%}" class="mr-5 hover:text-gray-900">Books</a> 
        {% if not request.user.is_authenticated %}       
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
        Enjoy reading {{request.user.username}}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">          
          </svg>
        </a>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">          
        </svg>
      </a>
      {% endif %}
    
    </div>
  </header>